"""Registry-dispatched, read-only collection; persistence lives in the Hub ledger."""
from __future__ import annotations

import re
from pathlib import Path, PurePosixPath
from importlib import import_module

from hub.connection_records import (RecordError, content_hash, credential_path_component,
                                    identifier, require)
from hub.connection_sources import SourceResolver, _root_path_allowed
from hub.connections import select_value
from hub.metric_sources import read_structured
from hub.metrics import VERSION, issue, metric, metric_catalog, utcnow, validate_metric

DOMAIN_ADAPTERS = {
    "manga": ("hub.metric_manga", "collect_manga"),
    "wechat": ("hub.metric_wechat", "collect_wechat"),
    "anime": ("hub.metric_catalogs", "collect_anime"),
    "pixel": ("hub.metric_catalogs", "collect_pixel"),
    "study": ("hub.metric_documents", "collect_study"),
    "story": ("hub.metric_documents", "collect_story"),
    "zarathustra": ("hub.metric_documents", "collect_zarathustra"),
    "cognitive": ("hub.metric_documents", "collect_cognitive"),
    "music": ("hub.metric_music", "collect_music"),
    "continuation": ("hub.metric_continuation", "collect_continuation"),
    "validation_runs": ("hub.metric_validation", "collect_validation_runs"),
    "downloader": ("hub.metric_saved_tools", "collect_downloader"),
    "workspace_checks": ("hub.metric_saved_tools", "collect_workspace_checks"),
    "hub_activity": ("hub.metric_hub_activity", "collect_hub_activity"),
    "mpv": ("hub.metric_mpv", "collect_mpv"),
    "client_fixture": ("hub.metric_fixture_report", "collect_fixture_report"),
    "storage_evidence": ("hub.metric_storage", "collect_storage"),
    "magnet_batch": ("hub.metric_magnet", "collect_magnet"),
    "jav_batch": ("hub.metric_magnet", "collect_jav"),
}
COMMON_PROJECT_FIELDS = {"adapter", "github_repository", "validation_reports"}
ADAPTER_PROJECT_FIELDS = {
    "declared": {"sources"},
    "novel": set(),
    "unmapped": set(),
    "manga": {"data_root", "batch_id", "review_db", "project_dbs"},
    "wechat": set(),
    "anime": {"metadata_root"},
    "pixel": {"metadata_root"},
    "study": set(),
    "story": set(),
    "zarathustra": {"editorial_root"},
    "cognitive": set(),
    "music": {"data_root"},
    "continuation": {"data_root", "universe_id"},
    "validation_runs": set(),
    "downloader": set(),
    "workspace_checks": set(),
    "hub_activity": set(),
    "mpv": {"project_files"},
    "client_fixture": {"report_root", "report_path"},
    "storage_evidence": {"evidence_root", "evidence_path"},
    "magnet_batch": set(),
    "jav_batch": {"data_root"},
}
DECLARED_SOURCE_FIELDS = {"path", "business_time", "metrics"}
DECLARED_METRIC_FIELDS = {"id", "unit", "selector", "operation", "dimensions", "counting_basis"}
REPORT_FIELDS = {
    "feature_report": {"id", "path", "format", "root", "source_files", "test_scope"},
    "gate_arrays": {"id", "path", "format", "root"},
    "universal_player_guard_result_v1": {"id", "path", "format", "root", "suite"},
}
DYNAMIC_CONFIG_FIELDS = {
    "value", "status", "quality", "reason", "observed_at", "business_at",
    "source_version", "candidate_revision", "submission_attempt", "rework_count",
    "completed", "accepted", "delivery",
}
DYNAMIC_DIMENSION_FIELDS = DYNAMIC_CONFIG_FIELDS | {
    "time", "timestamp", "version", "revision", "progress", "phase", "round",
    "count", "total", "result", "verdict", "decision", "business_time",
    "created_at", "updated_at", "started_at", "finished_at", "completed_at",
}


def metric_source_contract_schema():
    """Machine-readable stable declaration boundary; facts are exporter output."""
    return {
        "schema_version": VERSION,
        "config_validator": "hub.metric_collect.validate_metric_source_config",
        "top_level_fields": ["schema_version", "projects"],
        "project_common_fields": sorted(COMMON_PROJECT_FIELDS),
        "adapter_project_fields": {
            key: sorted(value) for key, value in ADAPTER_PROJECT_FIELDS.items()
        },
        "declared_source_fields": sorted(DECLARED_SOURCE_FIELDS),
        "declared_metric_fields": sorted(DECLARED_METRIC_FIELDS),
        "validation_report_fields": {
            key: sorted(value) for key, value in REPORT_FIELDS.items()
        },
        "forbidden_dynamic_fact_fields": sorted(DYNAMIC_CONFIG_FIELDS),
        "forbidden_dynamic_dimension_fields": sorted(DYNAMIC_DIMENSION_FIELDS),
        "path_rule": "all relative components and absolute roots use hub.connection_records.credential_path_component",
        "fact_rule": "configuration selects sources and definitions; values/status/times/versions are generated by collectors",
    }


def validate_metric_source_config(config, projects):
    require(type(projects) is dict, "metric project registry must be an object")
    require(type(config) is dict and set(config) == {"schema_version", "projects"},
            "metric source configuration fields do not match contract")
    require(config["schema_version"] == VERSION and type(config["projects"]) is dict,
            "invalid metric source configuration")
    require(set(ADAPTER_PROJECT_FIELDS) == {"declared", "novel", "unmapped"} | set(DOMAIN_ADAPTERS),
            "metric adapter schema drift")
    require(set(config["projects"]) <= set(projects), "metric config contains unknown projects")
    for project_id, spec in config["projects"].items():
        identifier(project_id, "metric project id")
        require(type(spec) is dict, "project source declaration must be an object")
        adapter = spec.get("adapter")
        require(type(adapter) is str and adapter in ADAPTER_PROJECT_FIELDS,
                "unsupported domain adapter")
        allowed = COMMON_PROJECT_FIELDS | ADAPTER_PROJECT_FIELDS[adapter]
        require(set(spec) <= allowed and not set(spec) & DYNAMIC_CONFIG_FIELDS,
                "project declaration contains unknown or dynamic fields")
        _validate_project_config(spec, adapter)
    return config


def _validate_project_config(spec, adapter):
    for key in ("metadata_root", "editorial_root", "data_root", "evidence_root", "report_root"):
        require(key not in spec or type(spec[key]) is str and Path(spec[key]).is_absolute(),
                "external metadata root must be an explicit absolute path")
        if key in spec:
            _root_path_allowed(Path(spec[key]))
    if "github_repository" in spec:
        require(type(spec["github_repository"]) is str
                and bool(re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", spec["github_repository"])),
                "invalid github repository binding")
    for key in ("batch_id", "universe_id"):
        if key in spec:
            identifier(spec[key], key)
    for key in ("review_db", "evidence_path", "report_path"):
        if key in spec:
            _relative_config_path(spec[key])
    if "project_dbs" in spec:
        require(type(spec["project_dbs"]) is dict and bool(spec["project_dbs"]),
                "project database bindings required")
        for project_id, path in spec["project_dbs"].items():
            identifier(project_id, "source project id")
            _relative_config_path(path)
    if "project_files" in spec:
        files = spec["project_files"]
        require(type(files) is list and 0 < len(files) <= 64,
                "bounded project files required")
        for path in files:
            _relative_config_path(path)
        require(len(files) == len(set(files)), "duplicate project files")

    sources = spec.get("sources", [])
    require(type(sources) is list, "declared sources must be a list")
    require(adapter != "declared" or bool(sources), "declared adapter needs sources")
    metric_identities = []
    for source in sources:
        require(type(source) is dict and {"path", "metrics"} <= set(source)
                and set(source) <= DECLARED_SOURCE_FIELDS,
                "declared source fields do not match contract")
        _relative_config_path(source["path"])
        if "business_time" in source:
            _selector(source["business_time"], "business_time")
        require(type(source["metrics"]) is list and bool(source["metrics"]),
                "declared source metrics required")
        for metric_spec in source["metrics"]:
            require(type(metric_spec) is dict
                    and {"id", "unit", "selector", "counting_basis"} <= set(metric_spec)
                    and set(metric_spec) <= DECLARED_METRIC_FIELDS,
                    "declared metric fields do not match contract")
            identifier(metric_spec["id"], "declared metric id")
            _bounded_text(metric_spec["unit"], "declared metric unit")
            _bounded_text(metric_spec["counting_basis"], "declared counting basis", 1000)
            _selector(metric_spec["selector"], "metric selector")
            operation = metric_spec.get("operation", "number")
            require(type(operation) is str and operation in {"number", "length", "bool"},
                    "invalid numeric operation")
            dimensions = metric_spec.get("dimensions", {})
            require(type(dimensions) is dict and len(dimensions) <= 12,
                    "invalid declared metric dimensions")
            for key, value in dimensions.items():
                identifier(key, "declared dimension")
                require(key not in DYNAMIC_DIMENSION_FIELDS,
                        "dynamic fact cannot be a declared dimension")
                require(type(value) in (str, int, bool) and len(str(value)) <= 200,
                        "invalid declared dimension value")
                if key == "scope":
                    identifier(value, "declared metric scope")
            metric_identities.append(content_hash([metric_spec["id"], dimensions]))
    require(len(metric_identities) == len(set(metric_identities)),
            "duplicate declared metric identities")

    reports = spec.get("validation_reports", [])
    require(type(reports) is list, "validation reports must be a list")
    require(adapter != "validation_runs" or bool(reports),
            "functional run reports required")
    report_ids = []
    for report in reports:
        require(type(report) is dict and {"id", "path", "format"} <= set(report),
                "invalid validation report")
        report_format = report["format"]
        require(type(report_format) is str and report_format in REPORT_FIELDS
                and set(report) <= REPORT_FIELDS[report_format],
                "validation report fields do not match contract")
        identifier(report["id"], "validation report id")
        _relative_config_path(
            report["path"], allow_glob=report_format == "universal_player_guard_result_v1"
        )
        if "root" in report:
            require(type(report["root"]) is str and Path(report["root"]).is_absolute(),
                    "invalid report root")
            _root_path_allowed(Path(report["root"]))
        if report_format == "universal_player_guard_result_v1":
            require(type(report.get("suite")) is str
                    and report["suite"] in {"core", "vlckit", "media", "raw"},
                    "guard suite required")
        selected = report.get("source_files")
        require((selected is None) == ("test_scope" not in report),
                "selected source files and test scope must be declared together")
        if selected is not None:
            require(type(selected) is list and 0 < len(selected) <= 64,
                    "invalid selected source file scope")
            for path in selected:
                _relative_config_path(path)
            require(len(selected) == len(set(selected)), "duplicate selected source files")
            identifier(report["test_scope"], "functional report test scope")
        report_ids.append(report["id"])
    require(len(report_ids) == len(set(report_ids)), "duplicate validation report ids")


def _relative_config_path(value, *, allow_glob=False):
    _bounded_text(value, "metric source path", 500)
    path = PurePosixPath(value)
    require(bool(path.parts) and "." not in path.parts and not path.is_absolute()
            and str(path) == value and "\\" not in value and ":" not in value
            and ".." not in path.parts,
            "metric source path must be canonical and relative")
    require(not any(part.lower() in {".git", ".ssh", ".cursor", ".codex", "credentials",
                                    "secrets", "cookies", "tokens", ".env"}
                    or part.lower().startswith(".env") or credential_path_component(part)
                    for part in path.parts),
            "protected metric source path")
    require(allow_glob or not any(char in value for char in "*?[]"),
            "metric source glob is not allowed")


def _selector(value, label):
    require(type(value) is list and 0 < len(value) <= 20,
            label + " must be a bounded path")
    require(all((type(part) is str and 0 < len(part) <= 160)
                or (type(part) is int and part >= 0) for part in value),
            label + " contains an invalid path component")


def _bounded_text(value, label, limit=200):
    require(type(value) is str and 0 < len(value.strip()) <= limit,
            label + " must be bounded nonempty text")


def collect_declared(root, project_id, observed_at, sources):
    """Explicit numeric selectors, not arbitrary code or governance completion."""
    rows, issues, versions = [], [], []
    for source in sources:
        path = source["path"]
        try:
            data, meta = read_structured(root, path)
            versions.append(meta["sha256"])
        except (OSError, RecordError, ValueError):
            data, meta = None, None
            issues.append(issue(project_id, "missing_or_invalid_source", path,
                                recovery_condition="Restore the declared metadata source; collection never runs its producer."))
        for spec in source["metrics"]:
            value, reason = None, "Declared source unavailable."
            business_at = None
            if data is not None:
                try:
                    raw = select_value(data, {"path": spec["selector"]})
                    op = spec.get("operation", "number")
                    if op == "length":
                        require(type(raw) in (list, dict), "count source must be a collection")
                        value = len(raw)
                    elif op == "bool":
                        require(type(raw) is bool, "boolean source required")
                        value = int(raw)
                    elif op == "number":
                        require(type(raw) in (int, float), "numeric source required")
                        value = raw
                    else:
                        raise RecordError("unsupported count operation")
                    reason = None
                except (RecordError, KeyError, IndexError, TypeError):
                    reason = "Declared numeric field unavailable or invalid."
                if source.get("business_time"):
                    try:
                        candidate = select_value(data, {"path": source["business_time"]})
                        from hub.connection_records import timestamp
                        timestamp(candidate, "business time")
                        business_at = candidate
                    except (RecordError, KeyError, IndexError, TypeError):
                        issues.append(issue(project_id, "invalid_business_time", path))
            version = content_hash([spec, value, reason, business_at])
            try:
                row = metric(project_id, spec["id"], value, spec["unit"], path + "#" + "/".join(map(str, spec["selector"])),
                    version, observed_at, dimensions=spec.get("dimensions"), business_at=business_at,
                    reason=reason, counting_basis=spec["counting_basis"])
            except RecordError:
                row = metric(project_id, spec["id"], None, spec["unit"], path, version, observed_at,
                    dimensions=spec.get("dimensions"), quality="invalid", reason="Numeric field failed contract validation.",
                    counting_basis=spec["counting_basis"])
            rows.append(row)
    return dict(metrics=rows, issues=issues, disposition="resolved" if rows and all(r["quality"] == "good" for r in rows) else "partial",
                source_version=content_hash(versions))


class MetricCollector:
    def __init__(self, root, *, clock=utcnow, remote_git=False, github_ci=False):
        self.resolver = SourceResolver(Path(root))
        self.registry = self.resolver.registry
        self.projects = self.resolver.projects
        self.clock = clock
        require(type(remote_git) is bool and type(github_ci) is bool, "remote options must be boolean")
        self.remote_git, self.github_ci = remote_git, github_ci
        path = Path(root) / "data/connections/metric_sources.yaml"
        self.config, _ = read_structured(Path(root), str(path.relative_to(root)))
        self.validate_config()
        # Input identity includes implementation, rather than relying only on a manually bumped version.
        modules = sorted(Path(__file__).parent.glob("metric*.py"))
        code = content_hash({p.name: content_hash(p.read_text()) for p in modules})
        self.identity = content_hash([self.resolver.authority, self.config, VERSION, code,
                                      {"remote_git": remote_git, "github_ci": github_ci}])

    def validate_config(self):
        return validate_metric_source_config(self.config, self.projects)

    def collect(self, project_id):
        project = self.projects[project_id]
        observed = self.clock()
        result = dict(project_id=project_id, observed_at=observed, disposition="partial",
                      metrics=[], metric_definitions=[], issues=[], source_versions={},
                      registry_binding=content_hash(project), collector_identity=self.identity)
        if project.get("local_presence", {}).get("status") == "removed_local" or project.get("current_state_status") == "removed_local":
            result["disposition"] = "removed_local"
            return result
        if project.get("connection_read_allowed", project.get("enabled")) is not True or project.get("access_profile") == "no_current_goal_access":
            result["disposition"] = "disabled"
            return result
        try:
            self.resolver._check_registry()
            registered = Path(project["root_path"]).expanduser()
            _root_path_allowed(registered)
            root = registered.resolve(strict=True)
            _root_path_allowed(root)
            require(root.is_dir(), "root not a directory")
        except (OSError, RecordError):
            result["disposition"] = "offline"
            result["issues"] = [issue(project_id, "root_unavailable", "registry:root_path")]
            return result
        from hub.metric_git import collect_git
        groups = [("git", lambda: collect_git(root, project_id, observed))]
        spec = self.config["projects"].get(project_id, {"adapter": "unmapped"})
        if self.remote_git or self.github_ci:
            from hub.metric_remote import collect_remote
            groups.append(("remote", lambda: collect_remote(root, project_id, observed, spec,
                remote_git=self.remote_git, github_ci=self.github_ci)))
        if spec["adapter"] == "novel":
            from hub.metric_novel import collect_novel
            groups.append(("business", lambda: collect_novel(root, project_id, observed)))
        elif spec["adapter"] in DOMAIN_ADAPTERS:
            module_name, function_name = DOMAIN_ADAPTERS[spec["adapter"]]
            domain_function = getattr(import_module(module_name), function_name)
            groups.append(("business", lambda: domain_function(root, project_id, observed, spec)))
        elif spec["adapter"] == "declared":
            groups.append(("business", lambda: collect_declared(root, project_id, observed, spec["sources"])))
        else:
            result["issues"].append(issue(project_id, "missing_business_mapping", "registry:" + project_id,
                recovery_condition="Bind actual domain/run metadata; governance complete is not business progress."))
        if spec.get("validation_reports") and spec["adapter"] != "validation_runs":
            from hub.metric_validation import collect_validation
            groups.append(("validation", lambda: collect_validation(root, project_id, observed, spec["validation_reports"])))
        for name, function in groups:
            try:
                group = function()
                for row in group["metrics"]:
                    try:
                        result["metrics"].append(validate_metric(row))
                    except RecordError:
                        result["issues"].append(issue(project_id, "invalid_metric", name + ":" + str(row.get("metric_id"))))
                result["issues"].extend(group["issues"])
                result["source_versions"][name] = group["source_version"]
                if name == "business":
                    result["disposition"] = group["disposition"]
                elif name == "validation" and group["disposition"] != "resolved":
                    result["disposition"] = "partial"
                elif group["disposition"] == "no_git":
                    result["issues"].append(issue(project_id, "no_git", "registry:root_path"))
            except (OSError, RecordError, ValueError, KeyError, TypeError) as exc:
                result["issues"].append(issue(project_id, "collector_failure", name,
                    recovery_condition="Inspect source schema and collector; no workflow was executed."))
        self.resolver._check_registry()
        require(registered.resolve(strict=True) == root, "root binding changed during collection")
        if result["issues"] and result["disposition"] == "resolved":
            result["disposition"] = "partial"
        result["metric_definitions"] = metric_catalog(result["metrics"])
        return result

    def refresh(self, store, request_id, project_ids=None):
        ids = project_ids or list(self.projects)
        require(len(ids) == len(set(ids)) and set(ids) <= set(self.projects), "unknown or duplicate projects")
        store.begin(request_id, ids, self.identity)
        receipts = []
        for pid in ids:
            previous = store.receipt(request_id, pid)
            receipts.append(previous if previous else store.save(request_id, self.collect(pid)))
        return receipts
